# file: redis.yml

- name: Install EPEL repo
  yum: name=http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm state=present
- name: Install Redis
  yum: name=redis state=present
- name: Start Redis
  service: name=redis state=started
